export enum Translation {
  BasicEnglish = "bbe",
}

export enum DefinedBookAlias {
  Genesis = "Gen",
  Exodus = "Exo",
  Leviticus = "Lev",
  Numbers = "Num",
  Deuteronomy = "Deu",
  Joshua = "Jos",
  Judges = "Jug",
  Ruth = "Rut",
  Samuel_1 = "1Sa",
  Samuel_2 = "2Sa",
  Kings_1 = "1Ki",
  Kings_2 = "2Ki",
  Chronicles_1 = "1Ch",
  Chronicles_2 = "2Ch",
  Ezra = "Ezr",
  Nehemiah = "Neh",
  Esther = "Est",
  Job = "Job",
  Psalms = "Psm",
  Proverbs = "Pro",
  Ecclesiastes = "Ecc",
  Song_of_Songs = "Son",
  Isaiah = "Isa",
  Jeremiah = "Jer",
  Lamentations = "Lam",
  Ezekiel = "Eze",
  Daniel = "Dan",
  Hosea = "Hos",
  Joel = "Joe",
  Amos = "Amo",
  Obadiah = "Oba",
  Jonah = "Jon",
  Micah = "Mic",
  Nahum = "Nah",
  Habakkuk = "Hab",
  Zephaniah = "Zep",
  Haggai = "Hag",
  Zechariah = "Zec",
  Malachi = "Mal",

  Matthew = "Mat",
  Mark = "Mak",
  Luke = "Luk",
  John = "Jhn",
  Acts = "Act",
  Romans = "Rom",
  Corinthians_1 = "1Co",
  Corinthians_2 = "2Co",
  Galatians = "Gal",
  Ephesians = "Eph",
  Philippians = "Phl",
  Colossians = "Col",
  Thessalonians_1 = "1Ts",
  Thessalonians_2 = "2Ts",
  Timothy_1 = "1Ti",
  Timothy_2 = "2Ti",
  Titus = "Tit",
  Philemon = "Phm",
  Hebrews = "Heb",
  James = "Jas",
  Peter_1 = "1Pe",
  Peter_2 = "2Pe",
  John_1 = "1Jn",
  John_2 = "2Jn",
  John_3 = "3Jn",
  Jude = "Jud",
  Revelation = "Rev",
}


export const Books: string[] = Object.keys(DefinedBookAlias).map((name: string) => /_\d/.test(name) ? name.split('_').reverse().join(' ') : name.replaceAll('_', ' '));