export enum Translation {
  BasicEnglish = "bbe",
  KingJamesVersion = "kjv",
}

export enum DefinedBookAlias {
  Genesis = "Gen",
  Exodus = "Exo",
  Leviticus = "Lev",
  Numbers = "Num",
  Deuteronomy = "Deu",
  Joshua = "Jos",
  Judges = "Jug",
  Ruth = "Rut",
  Samuel_1 = "1Sa",
  Samuel_2 = "2Sa",
  Kings_1 = "1Ki",
  Kings_2 = "2Ki",
  Chronicles_1 = "1Ch",
  Chronicles_2 = "2Ch",
  Ezra = "Ezr",
  Nehemiah = "Neh",
  Esther = "Est",
  Job = "Job",
  Psalms = "Psm",
  Proverbs = "Pro",
  Ecclesiastes = "Ecc",
  Song_of_Songs = "Son",
  Isaiah = "Isa",
  Jeremiah = "Jer",
  Lamentations = "Lam",
  Ezekiel = "Eze",
  Daniel = "Dan",
  Hosea = "Hos",
  Joel = "Joe",
  Amos = "Amo",
  Obadiah = "Oba",
  Jonah = "Jon",
  Micah = "Mic",
  Nahum = "Nah",
  Habakkuk = "Hab",
  Zephaniah = "Zep",
  Haggai = "Hag",
  Zechariah = "Zec",
  Malachi = "Mal",

  Matthew = "Mat",
  Mark = "Mak",
  Luke = "Luk",
  John = "Jhn",
  Acts = "Act",
  Romans = "Rom",
  Corinthians_1 = "1Co",
  Corinthians_2 = "2Co",
  Galatians = "Gal",
  Ephesians = "Eph",
  Philippians = "Phl",
  Colossians = "Col",
  Thessalonians_1 = "1Ts",
  Thessalonians_2 = "2Ts",
  Timothy_1 = "1Ti",
  Timothy_2 = "2Ti",
  Titus = "Tit",
  Philemon = "Phm",
  Hebrews = "Heb",
  James = "Jas",
  Peter_1 = "1Pe",
  Peter_2 = "2Pe",
  John_1 = "1Jn",
  John_2 = "2Jn",
  John_3 = "3Jn",
  Jude = "Jud",
  Revelation = "Rev",
}

const BookAbbr: { [key: string]: string[] } = {
  Genesis: ["Gen"],
  Exodus: ["Exo", "Ex"],
  Leviticus: ["Lev"],
  Numbers: ["Num"],
  Deuteronomy: ["Deu", "Deut"],
  Joshua: ["Jos", "Josh"],
  Judges: ["Jug", "Judg"],
  Ruth: ["Rut"],
  Samuel_1: ["1Sa", "1Sam"],
  Samuel_2: ["2Sa", "2Sam"],
  Kings_1: ["1Ki", "1Kgs"],
  Kings_2: ["2Ki", "2Kgs"],
  Chronicles_1: ["1Ch", "1Chr"],
  Chronicles_2: ["2Ch", "2Chr"],
  Ezra: ["Ezr"],
  Nehemiah: ["Neh"],
  Esther: ["Est", "Esth"],
  Job: ["Jb"],
  Psalms: ["Psm", "Ps", "Psalm"],
  Proverbs: ["Pro", "Prov"],
  Ecclesiastes: ["Ecc", "Eccl"],
  Song_of_Songs: ["Son", "Song"],
  Isaiah: ["Isa", "Is"],
  Jeremiah: ["Jer"],
  Lamentations: ["Lam"],
  Ezekiel: ["Eze", "Ezek"],
  Daniel: ["Dan"],
  Hosea: ["Hos"],
  Joel: ["Joe"],
  Amos: ["Amo"],
  Obadiah: ["Oba", "Obad"],
  Jonah: ["Jon"],
  Micah: ["Mic"],
  Nahum: ["Nah"],
  Habakkuk: ["Hab"],
  Zephaniah: ["Zep", "Zeph"],
  Haggai: ["Hag"],
  Zechariah: ["Zec", "Zech"],
  Malachi: ["Mal"],

  Matthew: ["Mat", "Mt", "Matt"],
  Mark: ["Mak", "Mk"],
  Luke: ["Luk", "Lk"],
  John: ["Jhn", "Jn"],
  Acts: ["Act"],
  Romans: ["Rom"],
  Corinthians_1: ["1Co", "1Cor"],
  Corinthians_2: ["2Co", "2Cor"],
  Galatians: ["Gal"],
  Ephesians: ["Eph"],
  Philippians: ["Phl", "Phil"],
  Colossians: ["Col"],
  Thessalonians_1: ["1Ts", "1Thes"],
  Thessalonians_2: ["2Ts", "2Thes"],
  Timothy_1: ["1Ti", "1Tim"],
  Timothy_2: ["2Ti", "2Tim"],
  Titus: ["Tit"],
  Philemon: ["Phm", "Phlm"],
  Hebrews: ["Heb"],
  James: ["Jas"],
  Peter_1: ["1Pe", "1Pet"],
  Peter_2: ["2Pe", "2Pet"],
  John_1: ["1Jn", "1Jhn"],
  John_2: ["2Jn", "2Jhn"],
  John_3: ["3Jn", "3Jhn"],
  Jude: ["Jud"],
  Revelation: ["Rev"],
}

for (let book in BookAbbr) {
  let abb = BookAbbr[book]
  let newAbb: string[] = []
  for (let ab of abb) {
    if (/^\d/.test(ab[0])) {
      let abb = ab[0] + " " + ab.slice(1)
      newAbb.push(abb, abb + ".")
    }
    newAbb.push(ab, ab + ".")
  }
  newAbb.push(
    book,
    /_\d/.test(book) ? book.split("_").reverse().join(" ") : book.replaceAll("_", " ")
  )
  BookAbbr[book] = [...new Set(newAbb)]
}

export { BookAbbr }
export enum PreferredAbbr {
  Genesis = "Gen",
  Exodus = "Exo",
  Leviticus = "Lev",
  Numbers = "Num",
  Deuteronomy = "Deut",
  Joshua = "Josh",
  Judges = "Judg",
  Ruth = "Ruth",
  Samuel_1 = "1 Sam",
  Samuel_2 = "2 Sam",
  Kings_1 = "1 Kgs",
  Kings_2 = "2 Kgs",
  Chronicles_1 = "1 Chr",
  Chronicles_2 = "2 Chr",
  Ezra = "Ezr",
  Nehemiah = "Neh",
  Esther = "Esth",
  Job = "Job",
  Psalms = "Ps",
  Proverbs = "Prov",
  Ecclesiastes = "Eccl",
  Song_of_Songs = "Song",
  Isaiah = "Is",
  Jeremiah = "Jer",
  Lamentations = "Lam",
  Ezekiel = "Ezek",
  Daniel = "Dan",
  Hosea = "Hos",
  Joel = "Joel",
  Amos = "Amos",
  Obadiah = "Obad",
  Jonah = "Jon",
  Micah = "Mic",
  Nahum = "Nah",
  Habakkuk = "Hab",
  Zephaniah = "Zeph",
  Haggai = "Hag",
  Zechariah = "Zech",
  Malachi = "Mal",

  Matthew = "Mt",
  Mark = "Mk",
  Luke = "Lk",
  John = "Jn",
  Acts = "Act",
  Romans = "Rom",
  Corinthians_1 = "1 Cor",
  Corinthians_2 = "2 Cor",
  Galatians = "Gal",
  Ephesians = "Eph",
  Philippians = "Phil",
  Colossians = "Col",
  Thessalonians_1 = "1 Thes",
  Thessalonians_2 = "2 Thes",
  Timothy_1 = "1 Tim",
  Timothy_2 = "2 Tim",
  Titus = "Tit",
  Philemon = "Phlm",
  Hebrews = "Heb",
  James = "Jas",
  Peter_1 = "1 Pet",
  Peter_2 = "2 Pet",
  John_1 = "1 Jn",
  John_2 = "2 Jn",
  John_3 = "3 Jn",
  Jude = "Jud",
  Revelation = "Rev",
}

export const Books: string[] = Object.keys(DefinedBookAlias).map((name: string) =>
  /_\d/.test(name) ? name.split("_").reverse().join(" ") : name.replaceAll("_", " ")
)
